---
title: "Практическая работа №7. Быстрое умножение теплицевой и циркулянтной матрицы на вектор"
date: "`r Sys.Date()`"
mainfont: SourceSansPro
output:
  pdf_document: 
    latex_engine: lualatex
    keep_tex: yes
    highlight: haddock
    fig_width: 8
    fig_height: 7
    fig_caption: yes
---

# **Циркулятная матрица**

Циркулянтная матрица - вид матрицы, получающеся в результате смещения влево первой строки матрицы на один элемент с переносом крайнего элемента на первую позицию справа в вектор-строке матрицы A. Итерационный перенос всей строки в рамках матрицы для каждой строки дает нам возможность строить циркулянтную матрицу:

$$
A^{CIRC} = \begin{pmatrix} a_0 & a_1 & a_2 & \dots & a_{n-1} \\
a_{n-1} & a_0 & a_1 & \dots & a_{n-2} \\ 
a_{n-2} & a_{n-1} & a_0 & \dots & a_{n-3} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
a_1 & a_2 & a_3 & \dots & a_{0}
\end{pmatrix}
$$

Данная матрица обладает свойством периодичности, в результате которой имеется несколько новых возможностей:

1. Не хранить матрицу полностью в памяти комптьютера, а получать её генератором, посредством повторного переноса первой строки.

2. Умножать такую матрицу на вектор не за $O(n^2)$, а за $O(n\cdot log_2(n)$ операций с помощью быстрого преобразования Фурье.

Во втором случае имеет место следующее равенство:

$$
A^{CIRC} \ @ \ u = f,\quad F^{-1}\left[\ F[A^{CIRC}_{0}] \cdot F[u]\ \right] \approx f,
$$
где $F[\cdot]\ -$ быстрое преобразование Фурье входного вектора, $F^{-1}[\cdot]\ -$ быстрое обратное преобразование Фурье входного вектора, $A \ @ \ b\ -$ матричное умножение матрицы на вектор по правилам линейной алгебры, $a \cdot b\ -$ поэлементное умножения векторов, $A^{CIRC}_{0}\ -$ первая строка циркулянтной матрицы $A^{CIRC}$.

Полученные выше выражения для умножения матрицы на вектор являеются идентичными с точностью до ошибок округления компьютерной арифметики и второй способ является эффективным методом умножения циркулянтной матрицы на вектор за короткое время.


# **Теплицева матрица**

Теплицева матрица -- конструктив, получающийся в рамках вычислительных методов решения задач математической физики при решении интегральных уравнений с ядром вида $K(x, y) = K(x - y)$, где зависимость от двух переменных представима в виде разницы двух аргументов. 

Пример такого ядра одномерной задачи распространения волны можно представить следующим образом:

$$
K(x, y) = K(x - y) = \frac{exp(1i \cdot k \cdot ||x - y||)}{2ik}; \ \ x, y\in \mathbb{R}.
$$
Здесь $K(x -y)\ -$ фундаментальная система решений неоднородного уравнения Гельмгольца в одномерном случае. Заметим, что функция является комплекснозначной и требует, на самом деле, больше вычислительных хитростей при умножении быстрым способом.

Или же можно представить более простое ядро:

$$
K(x, y) = K(x - y) = |x - y|; \ \ x, y\in \mathbb{R}.
$$

```{r}
x <- seq(-5, 5, 1)
y <- -4
k <- 2
exp(1i * k * abs(x - y)) / (2 * 1i * k)
```



$$
A^{TOEPL} = 
\begin{pmatrix} 
a_0 & a_1 & a_2 & \dots & a_{n-1} \\
a_{-1} & a_0 & a_1 & \dots & a_{n-2} \\ 
a_{-2} & a_{-1} & a_0 & \dots & a_{n-3} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
a_{-n+1} & a_{-n+2} & a_{-n+3} & \dots & a_{0}
\end{pmatrix}
$$

# **Постановка задачи**

